Few fixes for string type input
p4lang/tdi pull request #136
Opened 2024-07-17 06:25 UTC by ruchitg

1. If the input string is mentioned as hex, take the hex representation otherwise take the input bytes and convert them to ASCII for further processing.

2. Pass the length of input bytes/string. Use this length to copy and process the string bytes. This will mitigate the risk of buffer overflows, memory corruption or information leakage and other string issues which might occur while processing string without knowning it's length. The fix will also enable to pass and have NULL char and other special chars as part of string.

2024-07-18 04:17 UTC, swaroopsarma commented
i recommend to introduce a new c_frontend api for this purpose, and also a new member in the class rather than changing existing prototype. This will benefit in 2 ways. 1) backward compatibility 2)not impacting any other existing functionality if this is in use for any other platform

2024-07-18 04:18 UTC, swaroopsarma requested changes
i recommend to introduce a new c_frontend api for this purpose, and also a new member in the class rather than changing existing prototype. This will benefit in 2 ways. 1) backward compatibility 2)not impacting any other existing functionality if this is in use for any other platform

2024-07-18 08:28 UTC, satish153 approved these changes
LGTM

2024-07-18 08:28 UTC, satish153 commented on include/tdi/common/c_frontend/tdi_table_data.h
> +                                        const size_t s);
sz or size is a better choice for the variable name.

2024-07-18 14:38 UTC, saynb commented
I agree with adding a new API instead. This breaks backward compatibility

2024-07-19 14:29 UTC, swaroopsarma commented on include/tdi/common/c_frontend/tdi_table_data.h
> +                                                  const size_t s);
change it to length

2024-07-19 14:29 UTC, swaroopsarma commented on include/tdi/common/tdi_table_data.hpp
> +   * @param[in] length of the input string value
remove

2024-07-19 14:29 UTC, swaroopsarma commented on include/tdi/common/tdi_table_data.hpp
> +   * @param[in] s Size of string value
change the variable name to some string

2024-07-19 14:42 UTC, swaroopsarma commented on src/c_frontend/tdi_table_data_c.cpp
> +  if ((int)s > 0) {
does this need a type cast ?

2024-07-19 14:42 UTC, swaroopsarma commented on src/c_frontend/tdi_table_data_c.cpp
> +      for (int i = 1; i < (int)s; i++) {
does this need a typecast

2024-07-19 14:42 UTC, swaroopsarma commented on src/c_frontend/tdi_table_data_c.cpp
> +          str_val += val[i];
provide comment on why are we explicitly doing this instead of append

2024-07-22 06:52 UTC, swaroopsarma approved these changes
LGTM

2024-07-22 06:54 UTC, merged