adding c_frontend to tdi main
p4lang/tdi pull request #19
Opened 2022-03-02 19:41 UTC by weiqiand

2022-03-02 20:47 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_table.h
> +                                  const tdi_target_hdl *dev_tgt,
delete the deprecated table APIS and using generic flag support only.

2022-04-01 14:00 UTC, saynb requested changes

2022-04-04 20:10 UTC, weiqiand commented on include/tdi/arch/pna/pna_defs.h
> +enum tdi_match_type_pna_e {
yes. done

2022-04-05 01:12 UTC, saynb commented on src/c_frontend/tdi_table_key_c.cpp
> +  tdi::KeyFieldValueTernary<unsigned char> keyFieldValue(value1, value2, size);
I think these will can be uint64 templates. Only the calling ctor will change which is correct here

2022-04-05 04:26 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_info.h
> +                                         const tdi_dev_pipe_t **pipes);
The APIs which need tdi_info as input parameter, the prototype and implementation are all defined in tdi_info_c.cpp or tdi_info.h. Should we follow this convention or not. 
Yes. the C++ frontend function implementation is missing. Please added them.

2022-04-05 04:31 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_init.h
> +tdi_status_t tdi_p4_names_get(const tdi_dev_id_t dev_id, const char **p4_names);
The python CLI expect the dev_id not device_hdl during init_program

2022-04-05 04:31 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_init.h
> +tdi_status_t tdi_info_get(const tdi_dev_id_t dev_id,
The python CLI expect the dev_id not tdi_device_hdl during init_program

2022-04-05 04:56 UTC, saynb commented on include/tdi/common/c_frontend/tdi_init.h
> +tdi_status_t tdi_info_get(const tdi_dev_id_t dev_id,
The python CLI should be able to get the device_hdl through the C frontend via an API. We should probably add such a function

2022-04-05 04:58 UTC, saynb commented on include/tdi/common/c_frontend/tdi_table.h
> +                                    const tdi_id_t field_id,
This function can probably be changed to `tdi_key_field_match_type_get` and it should return `tdi_match_type_e`

2022-04-05 16:40 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_table.h
> +} tdi_table_api_type_t;
This structure is used for tdi_table_api_supported:
tdi_status_t tdi_table_api_supported(const tdi_table_hdl *table_hdl,
                                     tdi_table_api_type_t *apis,
                                     uint32_t *num_returned);

2022-04-05 16:42 UTC, saynb commented on include/tdi/common/c_frontend/tdi_table.h
> +} tdi_table_api_type_t;
https://github.com/p4lang/tdi/blob/main/include/tdi/common/tdi_defs.h#L49-L90

2022-04-05 21:14 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_table.h
> +bool tdi_generic_flag_support(void);
yes. done

2022-04-06 01:46 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_table.h
> + *
delete all the allocate functions

2022-04-07 03:24 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_table_operations.h
> +} tdi_table_operations_mode_t;
done. using the tdi_operations_type_e in the tdi_defs.h

2022-04-07 04:52 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_info.h
> +                                         const tdi_dev_pipe_t **pipes);
Since now the pipeline c++ implementation is not there.
It will be based on the C++ frontend implementation to make corresponding changes.

2022-04-07 04:55 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_learn.h
> +                                       const char **field_name_ret);
No creating separation of C_frontend for info now.

2022-04-07 05:03 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_session.h
> +
Yes. Delete this API .

2022-04-07 05:05 UTC, weiqiand commented on include/tdi/common/c_frontend/tdi_table.h
> +} tdi_table_api_type_t;
Yes removed

2022-04-08 03:17 UTC, saynb approved these changes
LGTM

2022-04-08 04:57 UTC, merged